# Introduction to Optimization (Root Finding)

Optimization is very commonly used in Finance. Some typical examples include - calculating portfolio weights, risk aversion coefficients, discount rates, etc. We will study this topic through an example. In this example, we will calculate the interest rate used in discounting cash-flows. 

$$PV(CF) = CF_0 = \frac{CF_1}{1+r} + \frac{CF_2}{(1+r)^2} + \frac{CF_3}{(1+r)^3} + ... \frac{CF_T}{(1+r)^T}$$

$$CF_0 = f(CF_i,r)$$


**PV(CF)** - Present value of cash-flows (magically given to us)

**$CF_i$**   - Cash-flow at year i

**f** - Is a non-linear function on 'r'

**Goal** - Is to calculate the 'r' that links CF_i to CF_0 

Before applying the optimization package in SciPy to the above problem, we will solve a simple quadratic equation of the form $ax^2 + bx + c = 0$.

In [65]:
# Applying the optimization function on a simple quadratic equation
import scipy.optimize
def quadratic_eq(x):
    return x**2 - 3*x + 2
solve = scipy.optimize.root(lambda x: quadratic_eq(x), [10], method='hybr')
#scipy.optimize.root?

In [66]:
# Printing the solution
print(solve)

    fjac: array([[-1.]])
     fun: array([0.])
 message: 'The solution converged.'
    nfev: 14
     qtf: array([-1.20703447e-12])
       r: array([-1.00000003])
  status: 1
 success: True
       x: array([2.])


In [63]:
# Generating random cash-flows
import numpy as np
cf_data = np.array([-100,30,20,50,80])
def c(r,cf_data):
    store_val = []
    for i in range(len(cf_data)):
        store_val.append(cf_data[i]/(1+r)**i)
    return np.sum(store_val)

solve_r = scipy.optimize.root(lambda r : c(r,cf_data), [0.1], method='hybr')
        

In [64]:
print(solve_r)

    fjac: array([[-1.]])
     fun: 9.237055564881302e-13
 message: 'The solution converged.'
    nfev: 8
     qtf: array([-2.30525806e-07])
       r: array([222.48821546])
  status: 1
 success: True
       x: array([0.22743067])


In [68]:
array = np.array([10,20,30,40])
np.diag(array)

array([[10,  0,  0,  0],
       [ 0, 20,  0,  0],
       [ 0,  0, 30,  0],
       [ 0,  0,  0, 40]])

# Programming Interview Questions


- **Matrix Operations** - Generating the correlation matrix by using only the covariance matrix. After studying linear regression, as an advanced study, you could try calculating the correlation matrix from the beta and covariance matrix. 

$$Corr(X,Y) = \frac{Cov(X,Y)}{\sigma_x \cdot \sigma_y}$$

$R$ - Correlation Matrix

$S$ - Array of Std Dev

$M$ - Covariance Matrix

$$M = diag(S) \cdot R \cdot diag(S) \implies R = (diag(S))^{-1} \cdot M (diag(S))^{-1}$$

In [163]:
# Using our stock data and recasting the dataframe
import numpy as np
import pandas as pd
df = pd.read_csv("stock_data.csv",parse_dates=['date'],na_values="C").dropna().reset_index()
df2 = df.groupby(['date','permno'])['total_returns'].sum().unstack().loc[:,[10137, 10051, 10057, 10028]].dropna().reset_index(drop=True)
cov = np.cov(df2,rowvar=False)
corr = np.corrcoef(df2,rowvar=False)
std = df2.std()
#print(cov.shape,corr.shape,std.shape)

In [164]:
corr

array([[ 1.        ,  0.20664862,  0.28741107, -0.1650564 ],
       [ 0.20664862,  1.        ,  0.36879598,  0.13422304],
       [ 0.28741107,  0.36879598,  1.        ,  0.05734076],
       [-0.1650564 ,  0.13422304,  0.05734076,  1.        ]])

In [165]:
cov

array([[ 0.00165183,  0.00104935,  0.0020737 , -0.00108881],
       [ 0.00104935,  0.01561044,  0.00818002,  0.0027219 ],
       [ 0.0020737 ,  0.00818002,  0.03151525,  0.0016522 ],
       [-0.00108881,  0.0027219 ,  0.0016522 ,  0.02634359]])

In [166]:
np.diag(std)

array([[0.04064266, 0.        , 0.        , 0.        ],
       [0.        , 0.12494174, 0.        , 0.        ],
       [0.        , 0.        , 0.17752536, 0.        ],
       [0.        , 0.        , 0.        , 0.16230708]])

In [170]:
# Generating the covariance matrix
np.matmul(np.diag(std),np.matmul(corr,np.diag(std)))

array([[ 0.00165183,  0.00104935,  0.0020737 , -0.00108881],
       [ 0.00104935,  0.01561044,  0.00818002,  0.0027219 ],
       [ 0.0020737 ,  0.00818002,  0.03151525,  0.0016522 ],
       [-0.00108881,  0.0027219 ,  0.0016522 ,  0.02634359]])

In [168]:
# Generating the correlation matrix
np.matmul(np.matmul(np.linalg.inv(np.diag(std)),cov),np.linalg.inv(np.diag(std)))

array([[ 1.        ,  0.20664862,  0.28741107, -0.1650564 ],
       [ 0.20664862,  1.        ,  0.36879598,  0.13422304],
       [ 0.28741107,  0.36879598,  1.        ,  0.05734076],
       [-0.1650564 ,  0.13422304,  0.05734076,  1.        ]])

- **Memoization** - Creating a fibonacci sequence without loops and using the memoization technique. Memoization involves caching values so future calls do not have to repeat the function calls.

In [84]:
# Task 1 - creating a Fibonacci sequence using loops
def fibonacci_loop(n):
    """Functions takes input integer 'n' and returns the n-th sequence of the fibonacci series (using loops)"""
    store = [1,1] # creating a list with integer 1
    i=2
    # Loop for generating the fibonacci sequence
    while i <n:
        store.append(store[i-2]+store[i-1])
        i=i+1
    #print(store)
    return store[n-1]

# Calling the function
fibonacci_loop(7)

for i in range(50):
    print(i,":",fibonacci_loop(i))

0 : 1
1 : 1
2 : 1
3 : 2
4 : 3
5 : 5
6 : 8
7 : 13
8 : 21
9 : 34
10 : 55
11 : 89
12 : 144
13 : 233
14 : 377
15 : 610
16 : 987
17 : 1597
18 : 2584
19 : 4181
20 : 6765
21 : 10946
22 : 17711
23 : 28657
24 : 46368
25 : 75025
26 : 121393
27 : 196418
28 : 317811
29 : 514229
30 : 832040
31 : 1346269
32 : 2178309
33 : 3524578
34 : 5702887
35 : 9227465
36 : 14930352
37 : 24157817
38 : 39088169
39 : 63245986
40 : 102334155
41 : 165580141
42 : 267914296
43 : 433494437
44 : 701408733
45 : 1134903170
46 : 1836311903
47 : 2971215073
48 : 4807526976
49 : 7778742049


In [94]:
# Task 2 - creating a Fibonacci sequence without using loops (without using Memoization)
from functools import lru_cache

@lru_cache(maxsize=1000)
def fibonacci(n):
    """Function takes input integer 'n' and returns the n-th sequence of the fibonacci series (no loops & no memoization)"""
    if n <= 2 : return 1
    else : return fibonacci(n-1)+fibonacci(n-2)

# Putting our function to the test
fibonacci(7)

for i in range(50):
    print(i,":",fibonacci(i))

0 : 1
1 : 1
2 : 1
3 : 2
4 : 3
5 : 5
6 : 8
7 : 13
8 : 21
9 : 34
10 : 55
11 : 89
12 : 144
13 : 233
14 : 377
15 : 610
16 : 987
17 : 1597
18 : 2584
19 : 4181
20 : 6765
21 : 10946
22 : 17711
23 : 28657
24 : 46368
25 : 75025
26 : 121393
27 : 196418
28 : 317811
29 : 514229
30 : 832040
31 : 1346269
32 : 2178309
33 : 3524578
34 : 5702887
35 : 9227465
36 : 14930352
37 : 24157817
38 : 39088169
39 : 63245986
40 : 102334155
41 : 165580141
42 : 267914296
43 : 433494437
44 : 701408733
45 : 1134903170
46 : 1836311903
47 : 2971215073
48 : 4807526976
49 : 7778742049


In [91]:
# Task 3 - creating a Fibonacci sequence without using loops (using Memoization)
fibonacci_cache = {}

def fibonacci_memoization(n):
    """Function takes input integer 'n' and returns the n-th sequence of the fibonacci series (no loops & with memoization)"""
    
    # Checking if the value n is in our cache
    if n in fibonacci_cache : return fibonacci_cache[n]
    
    # If not, then calculate the n-th value
    if n <= 2 : return 1
    else : 
        value = fibonacci_memoization(n-1)+fibonacci_memoization(n-2)
        fibonacci_cache[n] = value
        return value


for i in range(50):
    print(i,":",fibonacci_memoization(i))

0 : 1
1 : 1
2 : 1
3 : 2
4 : 3
5 : 5
6 : 8
7 : 13
8 : 21
9 : 34
10 : 55
11 : 89
12 : 144
13 : 233
14 : 377
15 : 610
16 : 987
17 : 1597
18 : 2584
19 : 4181
20 : 6765
21 : 10946
22 : 17711
23 : 28657
24 : 46368
25 : 75025
26 : 121393
27 : 196418
28 : 317811
29 : 514229
30 : 832040
31 : 1346269
32 : 2178309
33 : 3524578
34 : 5702887
35 : 9227465
36 : 14930352
37 : 24157817
38 : 39088169
39 : 63245986
40 : 102334155
41 : 165580141
42 : 267914296
43 : 433494437
44 : 701408733
45 : 1134903170
46 : 1836311903
47 : 2971215073
48 : 4807526976
49 : 7778742049


### Other Types of Interview Questions

- **Algorithm Question** - For example, take an array of length 'n' floats. Generate two arrays where the order of elements and  the size of array do not matter. The arrays have to be constructed such that the sum of the two arrays is minimized. You can use memoization/loops/external libraries. 
- **Order of complexity : Big-O** - Understanding the order of complexity of a loop, famous sorting/searching algorithms or your algorithms. 

### Other Topics

- Explaining a searching and sorting algorithm. 
- Advanced OOP - Inheritance, Sub-class, Meta-class, Composition, etc.


# Good Programming Practices

- Understanding that every program operates along multiple complexities - Time and Space complexities are the most common
- Making your code readable. Readable code that gives wrong output is better than an un-readable code that gives the right output.
- Setting your seed when you simulate random variables (very important for generating reproducible results).
- Commenting your code and adding doc-strings to your functions is very important when you want to revisit your code to understand what it does. It's easier to read through the comments than through code.
- Creating versions of your code (you might be interested in a Git repository). 
- Avoiding loops as much as you can and running efficient loops by vectorizing. 
- Although you feel smart when you nest multiple operations/functions on an object, long-run it is better to write one/two commands per line of code.

# Advanced Python Topics

- Git repository and Github
- Pandas - Multi index, Pivot, Melt, Stack, Unstack, Pickle, Concat 
- Numpy - LinAlg library, Random variable distributions
- Matplotlib - 3D plots, Interactive plots
- Multiprocessing (parallel computing)
- SQLite3 with Python
- Memoization
- Inheritance, Sub-classes, and Meta-classes
- Map, Reduce, and Filter
- Tensors
- NumBa (easily handles extremely large data sets)
- Logging and RaiseError for Exception Handling